version: '3'

services:
  db:
    image: couchbase/server-sandbox:6.0.1
    ports:
      - 8091-8094:8091-8094
      - 11210-11211:11210-11211
  build:
    build: .
    volumes:
      - ~/.terraform.d/plugins/:/app/bin/
    command:
      - cp
      - terraform-provider-couchbase
      - /app/bin/
